### ISSUE TITLE
submitted invalid Notification

### ISSUE THREAD

**Issue by sidbatra** [itspriddle/apnd#4]
I am on an ubuntu machine with rails 2.3.8, and the apnd gem 0.1.6.

Notifications are sent beautifully when I see APND::Notification.create or use apnd-push -- i.e. one at a time. However, when I try to do this -

notification1 = APND::Notification.new(
  :alert  => 'Red Alert!',
  :token  => 'My Token,
  :badge  => 99
)

APND::Notification.open_upstream_socket do |sock|
  sock.puts notification1
end

I see this in the log

[2011-02-17 05:29:56] Queue has 1 item
[2011-02-17 05:29:56] Sending notification for 'My Token'
[2011-02-17 05:36:46] 127.0.0.1:55122 opened connection
[2011-02-17 05:36:46] 127.0.0.1:55122 submitted invalid Notification
[2011-02-17 05:36:46] 127.0.0.1:55122 closed connection

and the notification doesn't go through.

Any help will be appreciated. Thanks.

**Comment by itspriddle** [comment]
Oops, I think that's a typo in the readme.

Try this:

```
APND::Notification.open_upstream_socket do |sock|
  sock.write(notification.to_bytes)
end
```

**Comment by sidbatra** [comment]
It worked!! Thank you so much for replying. Its so much more efficient now. Your work with apnd is awesome.
