### ISSUE TITLE
Sending Push Notification to Invalid Device ID Breaks All Following Notifications

### ISSUE THREAD

**Issue by sidbatra** [itspriddle/apnd#6]
Here is the usual upstream socket code

```
socket = APND::Notification.open_upstream_socket do |sock|
      users.each do |user|
        notification = APND::Notification.new(
                              :token  => user.iphone_device_id,
                              :badge  => user.unread_count
                              )
        puts notification.token
        sock.puts(notification.to_bytes + "\n")
      end
 end
```

If one of the iphone device ids is invalid (user deleted the app etc.) notifications are skipped for all the following iphone device ids.

This happens even if I use this code

```
    users.each do |user|
      APND::Notification.create(
                          :token  => user.iphone_device_id,
                          :badge  => user.unread_count
                          )
    end
```

As always, your help will be really appreciated.

**Comment by sidbatra** [comment]
Turns out its only a problem if one of the iphone device ids was obtained during debugging and wasn't a proper app store or IPA install. Don't worry about it :)

**Comment by itspriddle** [comment]
Good to know. If you run into it in production let me know. I'm running a small scale app with only about 10 devices, so I haven't run into invalid notifications.

If you do see it, it would be helpful if you knew how the token was invalid; formatting, or Apple rejecting it because your app isn't on the device anymore. I think the SSL connection with Apple is closed if an invalid notification is sent to them. I may need to add some detection for that and re-open the connection if that's the case.

**Comment by sidbatra** [comment]
My guess is that token invalidity can't be figured out based on the format. 

In this case, the problem started when a device id that had been obtained during testing (running the app on an iphone directly from xcode) was sent to the production apple server instead of the sandbox apple server.

It will be neat if it can be detected even though this shouldn't happen in production. Using a device id from a device where the app has been deleted doesn't cause any issues.

I am about to use your code for a large scale deployment. Are there any known vulnerabilities at scale? - on the order of several thousand notifications to different devices?

**Comment by itspriddle** [comment]
Should work fine for a large scale deployment, but there are two possible gotchas I can think of if you're dealing with _thousands_ of pending notifications at once:

Apple bottleneck: it's highly unlikely to happen, but in theory you could see a bottleneck writing thousands of notifications to the SSL socket. They're limited to 256 bytes in size each, so you'd probably only run into issues if you had really poor bandwidth on your server.

Event Machine Queue size: This is probably unlikely too, but if you has so many notifications they were queueing faster than they were being sent to Apple, the daemon would probably run out of memory and crash. Totally speculating on this though, my experience with Event Machine is limited to this project.

If you can, I'd suggest rolling out push support on your app for a few hundred devices first to make sure everything works as expected under load. If that works, try maybe 500, and then 1000 until you feel comfortable.

If it _is_ a problem, you might be able to get away with running multiple apnd daemons on different ports and partitioning your devices or alerts table.

I'm very interested in seeing how the gem works for larger apps, so please do keep me informed :)

**Comment by itspriddle** [comment]
Also - you'll probably want to implement feedback support in your app with that many devices. It's a work in progress, but I pushed [6c4feb6](https://github.com/itspriddle/apnd/commit/6c4feb6d19f0cfde69f6b0a9469cd88c00b6dc96) with feedback support.

**Comment by sidbatra** [comment]
I quite like the idea of having multiple apnd daemons (perhaps on different servers). My current implementation is structured for horizontal scaling. Thanks for your insight with the gotchas. Rest assured, I will start an issue :) if I run into trouble. 

Thanks again, checking out the new version, will keep you posted.
